name = "Move"
grammar = "move_on_aptos"
path_suffixes = ["move"]
line_comments = ["// "]
block_comment = { start = "/*", end = "*/", prefix = "* ", tab_size = 1 }
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "<", end = ">", close = false, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string", "comment"] },
]
word_characters = ["_"]
